name: mz_utils_example
description: Comprehensive example app demonstrating all mz_utils features
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  mz_utils:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mz_lints:
    path: ../packages/mz_lints

flutter:
  uses-material-design: true
