name: mz_utils
description: Production-ready Flutter and Dart utilities for state management, logging, observable collections, and rate limiting. Includes controllers, auto-disposal, debouncing, throttling, and useful extensions.
version: 0.0.1
repository: https://github.com/koiralapankaj7/mz_utils
issue_tracker: https://github.com/koiralapankaj7/mz_utils/issues
documentation: https://pub.dev/documentation/mz_utils/latest/

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
